### ISSUE TITLE
Adding custom concept for COVID-19 related markers.

### ISSUE THREAD

**Issue by mikkokotila** [autonomio/trauma-team-international#19]
Let's also add it to `analysis` table. It's good to note that some of these are overlapping with the markers that come from #18, so better check duplicates first and ignore them.

`item_id` list below:

```
[51241,
 51133,
 51143,
 51244,
 51245,
 51240,
 51264,
 51265,
 51266,
 50805,
 50811,
 50814,
 50852,
 50855,
 51212,
 51222,
 51223,
 51224,
 51225,
 51285,
 50889,
 50861,
 50878,
 50883,
 50884,
 50885,
 50862,
 50809,
 50931,
 50912,
 51214,
 50915,
 51196]
```

**Comment by mikkokotila** [comment]
@pdey let's use `min` and `max` first day values for these, so it's consistent with what we already have in `analysis` from firstdaylabls concept.

**Comment by pdey** [comment]
After filtering out the items that were already present in firstdaylabs concept, we are left with the following item ids. At some point we need the **upper bound sanity checks** for these markers, similar to how its done in `firstdaylabs` concept.
@mikkokotila - can you create an issue to follow this later.

      -- comment is: LABEL | CATEGORY | FLUID | NUMBER OF ROWS IN LABEVENTS
      50868, -- ANION GAP | CHEMISTRY | BLOOD | 769895
      50862, -- ALBUMIN | CHEMISTRY | BLOOD | 146697
      51144, -- BANDS - hematology
      50882, -- BICARBONATE | CHEMISTRY | BLOOD | 780733
      50885, -- BILIRUBIN, TOTAL | CHEMISTRY | BLOOD | 238277
      50912, -- CREATININE | CHEMISTRY | BLOOD | 797476
      50902, -- CHLORIDE | CHEMISTRY | BLOOD | 795568
      50806, -- CHLORIDE, WHOLE BLOOD | BLOOD GAS | BLOOD | 48187
      50931, -- GLUCOSE | CHEMISTRY | BLOOD | 748981
      50809, -- GLUCOSE | BLOOD GAS | BLOOD | 196734
      51221, -- HEMATOCRIT | HEMATOLOGY | BLOOD | 881846
      50810, -- HEMATOCRIT, CALCULATED | BLOOD GAS | BLOOD | 89715
      51222, -- HEMOGLOBIN | HEMATOLOGY | BLOOD | 752523
      50811, -- HEMOGLOBIN | BLOOD GAS | BLOOD | 89712
      50813, -- LACTATE | BLOOD GAS | BLOOD | 187124
      51265, -- PLATELET COUNT | HEMATOLOGY | BLOOD | 778444
      50971, -- POTASSIUM | CHEMISTRY | BLOOD | 845825
      50822, -- POTASSIUM, WHOLE BLOOD | BLOOD GAS | BLOOD | 192946
      51275, -- PTT | HEMATOLOGY | BLOOD | 474937
      51237, -- INR(PT) | HEMATOLOGY | BLOOD | 471183
      51274, -- PT | HEMATOLOGY | BLOOD | 469090
      50983, -- SODIUM | CHEMISTRY | BLOOD | 808489
      50824, -- SODIUM, WHOLE BLOOD | BLOOD GAS | BLOOD | 71503
      51006, -- UREA NITROGEN | CHEMISTRY | BLOOD | 791925
      51301, -- WHITE BLOOD CELLS | HEMATOLOGY | BLOOD | 753301
      51300  -- WBC COUNT | HEMATOLOGY | BLOOD | 2371
